# GitHub Actions Workflow created for handling the release process based on the draft release prepared
# with the Build workflow. Running the publishPlugin task requires the PUBLISH_TOKEN secret provided.

name: Release
on:
  workflow_dispatch

jobs:

  # Patch changelog, commit and push to the current repository
  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Testing
        run: |
          ./patch-changelog.sh
