name: Test
on:
  workflow_dispatch:

jobs:
  # Run verifyPlugin and test Gradle tasks
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.3.4

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      # Run Qodana inspections
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2.1-eap
        with:
          project-dir: ${{ github.workspace }}/plugin
          results-dir: ${{ github.workspace }}/plugin/qodana