name: Test
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Dummy
        run: pwd
