name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          ls -la
          dotnet --list-sdks
          dotnet --list-runtimes

      - name: Setup .NET Core SDK '2.1.x'
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: '2.1.x'

      - name: Test
        run: |
          ls -la
          dotnet --list-sdks
          dotnet --list-runtimes

      - name: Setup .NET Core SDK '3.1.x'
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: '3.1.x'

      - name: Test
        run: |
          ls -la
          dotnet --list-sdks
          dotnet --list-runtimes

      - name: Setup .NET Core SDK '5.0.x'
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: '5.0.x'

      - name: Test
        run: |
          ls -la
          dotnet --list-sdks
          dotnet --list-runtimes

      - name: Fetch Sources
        uses: actions/checkout@v2.3.4

      - name: Test
        run: |
          ls -la
          dotnet --list-sdks
          dotnet --list-runtimes

      - name: Install Dependencies
        working-directory: backend
        run: dotnet restore

      - name: Run Tests
        working-directory: backend
        run: dotnet test --no-restore --verbosity normal
